spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:sqlite:db/praha_rent_apartments_watchdog.sqlite
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 15
bot:
  chat-id: ${CHAT_ID}
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}

watchdogs:
  check-delay: 5 # minutes
  expats:
    base-url: https://www.expats.cz
    search-url: /praguerealestate/apartments/for-rent/prague-region?re_advert_subtype=2-plus-kk-1-bedroom,2-plus-1-1-bedroom,3-plus-kk-2-bedrooms&re_building_condition=very-good-condition,developer-project,new-construction,renovated&ruian_prague_district=prague-1,prague-2,prague-3,prague-7,prague-8,prague-9&re_furnished=yes-furnished&advert_price_to=30000