spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_apartments_watchdog_bot?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 15
bot:
  chat-id: ${CHAT_ID}
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}

watchdogs:
  check-delay: 1_800_000 # 30 minutes
  expats:
    base-url: https://www.expats.cz
    search-url: /praguerealestate/apartments/for-rent/prague-region?re_advert_subtype=2-plus-kk-1-bedroom,2-plus-1-1-bedroom,3-plus-kk-2-bedrooms&re_furnished=yes-furnished,partially&advert_price_to=30000